@ToDoAPI_HostAddress = https://localhost:7220

POST {{ToDoAPI_HostAddress}}/api/todoitems
Content-Type: application/json
{
  "name": "sleep",
  "isComplete": true
}

###

GET {{ToDoAPI_HostAddress}}/api/students/
Accept: application/json

###

@id=1
GET {{ToDoAPI_HostAddress}}/api/todoitems/{{id}}
Accept: application/json

###