// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoAPI.Data;

#nullable disable

namespace ToDoAPI.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoAPI.Models.Attendance", b =>
                {
                    b.Property<int>("attendance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("attendance_id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("enrollment_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("attendance_id");

                    b.HasIndex("enrollment_id");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("ToDoAPI.Models.Classes", b =>
                {
                    b.Property<int>("class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("class_id"));

                    b.Property<string>("academic_year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("room")
                        .HasColumnType("int");

                    b.HasKey("class_id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("ToDoAPI.Models.Enrollments", b =>
                {
                    b.Property<int>("enrollment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enrollment_id"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("enrollment_id");

                    b.HasIndex("ClassID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("ToDoAPI.Models.Grades", b =>
                {
                    b.Property<int>("grade_id")
                        .HasColumnType("int");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.Property<int>("enrollment_id")
                        .HasColumnType("int");

                    b.Property<string>("grade_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("grade_id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("ToDoAPI.Models.Students", b =>
                {
                    b.Property<int>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_id"));

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("enrollment_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ToDoAPI.Models.Subjects", b =>
                {
                    b.Property<int>("subject_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subject_id"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<string>("subject_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subject_id");

                    b.HasIndex("class_id")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ToDoAPI.Models.Teachers", b =>
                {
                    b.Property<int>("teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacher_id"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("teacher_id");

                    b.HasIndex("class_id")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ToDoAPI.Models.Attendance", b =>
                {
                    b.HasOne("ToDoAPI.Models.Enrollments", "enrollments")
                        .WithMany("Attendances")
                        .HasForeignKey("enrollment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("enrollments");
                });

            modelBuilder.Entity("ToDoAPI.Models.Enrollments", b =>
                {
                    b.HasOne("ToDoAPI.Models.Classes", "Classes")
                        .WithMany("enrollments")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoAPI.Models.Students", "Student")
                        .WithMany("enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ToDoAPI.Models.Grades", b =>
                {
                    b.HasOne("ToDoAPI.Models.Enrollments", "enrollments")
                        .WithMany("Grades")
                        .HasForeignKey("grade_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("enrollments");
                });

            modelBuilder.Entity("ToDoAPI.Models.Subjects", b =>
                {
                    b.HasOne("ToDoAPI.Models.Classes", "classes")
                        .WithOne("subjects")
                        .HasForeignKey("ToDoAPI.Models.Subjects", "class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classes");
                });

            modelBuilder.Entity("ToDoAPI.Models.Teachers", b =>
                {
                    b.HasOne("ToDoAPI.Models.Classes", "classes")
                        .WithOne("teachers")
                        .HasForeignKey("ToDoAPI.Models.Teachers", "class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classes");
                });

            modelBuilder.Entity("ToDoAPI.Models.Classes", b =>
                {
                    b.Navigation("enrollments");

                    b.Navigation("subjects")
                        .IsRequired();

                    b.Navigation("teachers")
                        .IsRequired();
                });

            modelBuilder.Entity("ToDoAPI.Models.Enrollments", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("ToDoAPI.Models.Students", b =>
                {
                    b.Navigation("enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
